INSERT INTO `estaciones` (nombre, conexion) VALUES
("San Javier","si-directa"),
("Santa Lucia","no"),
("Floresta","si-indirecta"),
("Estadio","si-directa"),
("Suramericana","si-directa"),
("Cisneros","si-indirecta"),
("La Estrella","no"),
("Sabaneta","si-indirecta"),
("Itaguí","si-indirecta"),
("Envigado","si-indirecta"),
("Ayura","no"),
("Aguacatala","no"),
("Poblado","no"),
("Industriales","si-indirecta"),
("Exposiciones","no"),
("Alpujarra","no"),
("San Antonio","si-doble"),
("Parque Berrio","si-directa"),
("Prado","no"),
("Hospital","si-directa"),
("Universidad","si-directa"),
("Caribe","si-indirecta"),
("Tricentenario","no"),
("Acevedo","si-directa"),
("Madera","no"),
("Bello","si-indirecta"),
("Niquia","no"),
("San José","si-indirecta"),
("Pabellón de agua","no"),
("Bicentenario","no"),
("Buenos Aires","no"),
("Miraflores","si-indirecta"),
("Loyola","no"),
("Alejandro Echavarría","no"),
("Oriente","si-directa"),
("Las Torres","no"),
("Villa Sierra","no"),
("Juan XXIII","no"),
("Vallejuelos","no"),
("La Aurora","no"),
("Andalucía","no"),
("Popular","no"),
("Santo Domingo","si-directa"),
("Arví","si-directa"),
("El Pinal","no"),
("Trece de noviembre","no"),
("Sena","no"),
("Doce de octubre","no"),
("El progreso","no"),
("Universal","no"),
("Córdoba","no"),
("Pilarica","no"),
("Ciudadela universitaria","no"),
("Facultad de minas","si-indirecta"),
("Los colores","no"),
("Calasanz","no"),
("Los pinos","no"),
("Laureles","no"),
("Santa Gema","no"),
("Villa de Aburra","no"),
("La palma","si-doble"),
("Viva Envigado","no"),
("Villas de vallejuelos","no"),
("Puente fundadores","no"),
("Portón de Alcalá","no"),
("Pista de patinaje","no"),
("Parque Débora Arango","no"),
("Metro envigado sur","si-indirecta"),
("Metro envigado norte","si-indirecta"),
("Los urapanes","no"),
("La última estación","no"),
("Iglesia Alcalá","no"),
("Guanteros","no"),
("Envigado centro","no"),
("El MUA","no"),
("Auxiliar metro Envigado","si-indirecta"),
("Villa paula","no"),
("Puente pandequeso I","no"),
("Puente pandequeso II","no"),
("Parque de Itaguí","no"),
("Parque el artista","no"),
("Metróplus cami","no"),
("Metro itaguí II","si-indirecto"),
("Metro itaguí I","si-indirecta"),
("Los naranjos","no"),
("Ideas","no"),
("Doña maría","no"),
("Bahía ciclovía","no"),
("Villa carlota","no"),
("Telemedellín","no"),
("Río aburrá","no"),
("Politécnico","no"),
("MAM","no"),
("Industriales metro","si-indirecta"),
("Ciudad del río","no"),
("Calle 19A villa carlota","no"),
("Parque Bello","no"),
("Metro bello","si-indirecta"),
("Robledo","si-indirecta"),
("Campus nacional","no"),
("San cayetano","si-indirecta"),
("Paraná","no"),
("Santa ana","no"),
("Sabaneta metro","si-indirecta"),
("Sabaneta centro","no"),
("Puente de la 77 sur","no"),
("Parque 4 elementos","no"),
("Las vegas 69 sur","no"),
("La barquereña","no"),
("Entre amigos","no"),
("Calle nueva","no"),
("Biblioteca sabaneta","no"),
("Aves maría","no"),
("SIU-UdeA","no"),
("Plaza mayor (EC)","si-indirecta"),
("Plaza de la libertad","no"),
("Pies descalzos I","no"),
("Pies descalzos II","no"),
("Parque de las luces I","no"),
("Parque de las luces II","no"),
("Parque Berrio (EC)","si-indirecta"),
("Palacio de la cultura","si-indirecta"),
("Palacé","no"),
("Museo de antioquia","si-indirecta"),
("Málaga","si-indirecta"),
("Distrito creativo","no"),
("Dián alpujarra","no"),
("Coltejer","no"),
("Area metropolitana","no"),
("Universidad (EC)","si-indirecta"),
("Ruta n","no"),
("Moravia","no"),
("Unidad deportiva de belén","no"),
("Rosales (EC)","si-indirecta"),
("Picacha la 76","no"),
("Parques del rio","no"),
("Nutibara (EC)","si-indirecta"),
("Maria luisa calle","no"),
("La 33","no"),
("Juan pablo II","no"),
("Industriales metróplus","si-indirecta"),
("Cafetero","no"),
("Bulerias","no"),
("UPB","no"),
("Unicentro","no"),
("Suramericana (EC)","si-indirecta"),
("Segundo parque de laureles","no"),
("Santa teresita","no"),
("San pedro y san pablo","no"),
("San juan","no"),
("San joaquín","no"),
("Salazar y herrera","no"),
("Primer parque de laureles","no"),
("Pedro nel gómez","no"),
("Parque san joaquin","no"),
("Parque de los mangos","no"),
("Parque de los enamorados","no"),
("Orquídeas","no"),
("María mulata","no"),
("Los colores","no"),
("La 65","no"),
("Florida nueva","no"),
("Floresta (EC)","si-indirecta"),
("Estadio (EC)","si-indirecta"),
("Colombia","no"),
("Circular primera","no"),
("Carlos e restrepo","no"),
("Calle 51 los colores","no"),
("Cacique candela","no"),
("Batallón","no"),
("UdeM","si-directa"),
("Los alpes","si-directa"),
("Parque belén","si-directa"),
("Rosales","si-doble"),
("Fátima","si-directa"),
("Nutibara","si-doble"),
("Industriales (MP)","si-doble"),
("Plaza mayor","si-indirecta"),
("Cisneros (MP)","si-indirecta"),
("Minorista","no"),
("Chagualo","no"),
("Ruta N UdeA","no"),
("Hospital (MP)","si-directa"),
("Palos verdes","si-indirecta"),
("Gardel","si-directa"),
("Manrique","si-directa"),
("Las esmeraldas","si-directa"),
("Berlín","si-directa"),
("Parque de aranjuez","si-directa"),
("Catedral","no"),
("La playa","no"),
("Barrio colón","no"),
("Perpetuo socorro","no"),
("Barrio colombia","no");




